api_version = "2025-10"

[[extensions]]
name = "t:name"
handle = "product-sync"
type = "ui_extension"
uid = "d69923de-da6b-09e8-3775-875ab81d8d1ba0e50c09"

[[extensions.targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.product-details.action.render"

[[extensions]]
name = "t:name"
handle = "product-sync-bulk"
type = "ui_extension"
uid = "e4a86177-4890-4303-b26e-144fcc8b414d"

[[extensions.targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.product-index.selection-action.render"
