# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ab540b86ceb52c60bd693d49ad5a3520"
name = "kitsuchan"
application_url = "https://kitsuchan-446695340286.australia-southeast1.run.app/"
embedded = true
handle = "kitsuchan"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
uri = "/webhooks/app/uninstalled"
topics = ["app/uninstalled"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,read_products,read_themes,write_products,write_themes,read_customers"

[auth]
redirect_urls = [
  "https://kitsuchan-446695340286.australia-southeast1.run.app/auth/callback",
]

[pos]
embedded = false
