api_version = "2025-10"

[[extensions]]
name = "t:name"
handle = "pvx-sync"
type = "ui_extension"
uid = "608e17bd-8899-1a0c-9146-c43b2dcda0acb09635d5"

[[extensions.targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.product-details.action.render"

[[extensions]]
name = "t:name"
handle = "pvx-sync-bulk"
type = "ui_extension"
uid = "4da9a59c-5450-4961-b5a7-17f98515203f"

[[extensions.targeting]]
module = "./src/ActionExtension.jsx"
target = "admin.product-index.selection-action.render"
