import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const LIVE_FILENAME = 'shopify.app.live.toml';

/**
 * Writes `shopify.app.live.toml` from `shopify.app.toml` with production URLs.
 * Use with `shopify app deploy -c live`. `publicOrigin` is https origin without trailing slash.
 */
export function writeShopifyAppLiveToml(root, publicOrigin) {
  const base = String(publicOrigin).trim().replace(/\/+$/u, '');
  if (!base.startsWith('https://')) {
    throw new Error('writeShopifyAppLiveToml: publicOrigin must be an https:// URL');
  }
  const appUrl = `${ base }/`;
  const callback = `${ base }/auth/callback`;

  const srcPath = join(root, 'shopify.app.toml');
  const raw = readFileSync(srcPath, 'utf8');

  let out = raw
    .replace(/application_url\s*=\s*['"][^'"]*['"]/u, `application_url = '${ appUrl }'`)
    .replace(/automatically_update_urls_on_dev\s*=\s*true/u, 'automatically_update_urls_on_dev = false')
    .replace(
      /(\[auth\]\s*\n)redirect_urls\s*=\s*\[[\s\S]*?\]/u,
      `$1redirect_urls = [\n  '${ callback }',\n]`,
    );

  const banner = `# Generated by scripts/gcp-deploy.mjs — do not edit. Source: shopify.app.toml + Cloud Run URL.\n\n`;
  writeFileSync(join(root, LIVE_FILENAME), banner + out, 'utf8');
  return join(root, LIVE_FILENAME);
}

export { LIVE_FILENAME };
